#cloud-config
package_upgrade: true
packages:
  - curl
  - git
  - install
  - ca-certificates
  - gnupg
  - lsb-release
  - jq
  - nodejs
runcmd:
  # Installing dotnet
  - sudo apt-get install -y dotnet-sdk-8.0
